import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

help(mpl)
print(dir(mpl))
print(mpl)

plt.style.use('ggplot')
print(plt)
print(plt.style)

fig = plt.figure()
ax = plt.axes()
plt.savefig('plots/fig.png')
# plt.draw()
# plt.pause(1)
# plt.show()
# plt.clf()

plt.figure()
plt.ion()
ax1 = plt.subplot(211)
plt.title('test', fontsize=8)
plt.xlim(-1700, 1700)
plt.ylabel('x-axis')
plt.xlabel('y-axis')
plt.grid()
plt.savefig('plots/stackoverflow.png')
# plt.draw()
# plt.pause(1)
# plt.show()
# plt.clf()


x = np.linspace(0, 10, 1000)
y = np.sin(x)
plt.figure()
axis = plt.axes()
axis.plot(x, y)
plt.savefig('plots/sin_basic.png')
# plt.draw()
# plt.pause(1)
# plt.show()
# plt.clf()

x = np.linspace(0, 10, 1000)
y = np.sin(x)
plt.figure()
axis = plt.axes()
axis.plot(x, y)
plt.xlabel('x')
plt.ylabel('y')
plt.title('function sin(x)')
plt.xlim(2, 8)
plt.ylim(0, 1)
plt.savefig('plots/sin_modified.png')
# plt.draw()
# plt.pause(1)
# plt.show()
# plt.clf()
